### ISSUE TITLE
Gravestone block itself doesn't have a name

### ISSUE THREAD

**Issue by jawsawn** [Yopu/OpenGrave#1]
Just for the mention.
Amazing lightweight mod! I can suggest to make it so the grave itself breaks faster without a pick.

Also am I allowed to use this modification on a modpack? Keep the good work!

**Comment by Yopu** [comment]
Feel free to use in modpacks.

**Comment by Yopu** [comment]
Fixed in: https://github.com/Yopu/OpenGrave/commit/397df31dae5da7941caa93e842f89841dc466ac0
Thanks for the input!
