### ISSUE TITLE
Dying underwater doesn't create any graves.

### ISSUE THREAD

**Issue by jawsawn** [Yopu/OpenGrave#2]
I might think thats more likely because of graves drop their items if theres nothing below them.

Also mind adding a config file for making graves indestructible? Like they still work when theres no block under them or something? Enderdragon-proof?

**Comment by Yopu** [comment]
When dying under water, your grave should "float up" to the top water block.

**Comment by jawsawn** [comment]
Tested it. So I closed it.

**Comment by Yopu** [comment]
Thanks
